### ISSUE TITLE
RSK inside UIView

### ISSUE THREAD

**Issue by umair2ooo** [ruslanskorb/RSKGrowingTextView#16]
![screen shot 2019-02-14 at 2 28 26 pm](https://user-images.githubusercontent.com/2729279/52777089-d599cc80-3064-11e9-8f73-421062104579.png)
Hi
Hope you will be good
when I put RSKTV inside a container
and container is the input accessory view of UICollectionVIew
in that case it is not expanding
what could be reason?

I put In viewDidLoad
self.growingTextView.translatesAutoresizingMaskIntoConstraints = false

See the picture
I need something like that
I made the IBOutlet of this whole container and this is the inputaccessoryview

please guide
Thanks

**Comment by ruslanskorb** [comment]
This is because you are using a `UIView` as the input accessory view, not a `RSKGrowingTextView`.

First of all, you should add all the necessary constraints.

Then, you should create a subclass `UIView`, override `intrinsicContentSize` and return something other than `UIView.noIntrinsicMetric` for `height`.

Also, you should set `translatesAutoresizingMaskIntoConstraints` of your input accessory view to `false` from the code.

**Comment by umair2ooo** [comment]
Thanks for your response
Let me try
will update you
