### ISSUE TITLE
blinking black screen & textview not appearing above keyboard

### ISSUE THREAD

**Issue by 24purnimasingh** [ruslanskorb/RSKGrowingTextView#26]

**Comment by ruslanskorb** [comment]
> Attaching video for your reference.
>
> Uploading Screen Recording 2023-11-21 at 3.50.08 PM.mov…

@24purnimasingh It looks like your video got lost somewhere. Could you re-upload it?

**Comment by 24purnimasingh** [comment]
https://github.com/ruslanskorb/RSKGrowingTextView/assets/85173836/42435118-ad93-4705-99a5-c4c1ea79cbb5

**Comment by ruslanskorb** [comment]
@24purnimasingh

If you are using Auto Layout, then I would recommend that you check your constraints. The user of the framework is responsible for positioning `RSKGrowingTextView`.

If you are sure that the issue is in `RSKGrowingTextView`, then I will ask you to separate it into a separate test project and send me a link to its repository. You can also try to reproduce the problem in [the example project](https://github.com/ruslanskorb/RSKGrowingTextView/tree/develop/RSKGrowingTextViewExample) if this will speed up the process.
